# Generated by Django 5.1.2 on 2026-08-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_movimientostock_precio_costo_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_thumb',
            field=models.ImageField(blank=True, help_text='Miniatura responsiva (auto)', null=True, upload_to='productos/'),
        ),
    ]
