# Generated by Django 5.1.2 on 2026-08-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_producto_imagen_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_thumb_media',
            field=models.ImageField(blank=True, help_text='Variante media 627px (auto)', null=True, upload_to='productos/'),
        ),
    ]
