# Generated by Django 5.1.2 on 2026-04-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen recomendada: 1920x800px', upload_to='banners/')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitulo', models.CharField(blank=True, max_length=300, null=True)),
                ('texto_boton', models.CharField(default='VER COLECCIÓN', max_length=50)),
                ('enlace_boton', models.CharField(default='#tienda', max_length=500)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banner Principal',
                'verbose_name_plural': 'Banners Principales',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ResenaComunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Foto de la clienta (preferiblemente cuadrada)', upload_to='comunidad/')),
                ('nombre_cliente', models.CharField(help_text='Ej: @maria_perez o María P.', max_length=100)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Reseña de Comunidad',
                'verbose_name_plural': 'Reseñas de Comunidad',
                'ordering': ['orden'],
            },
        ),
    ]
