server {
    listen 80;
    server_name byheilynaguilar.com www.byheilynaguilar.com;
    
    # Redirección 301 a HTTPS (SEO Best Practice)
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl; # Certbot gestionará los certificados, pero aquí activamos la escucha segura
    server_name byheilynaguilar.com www.byheilynaguilar.com;

    # Seguridad: Ocultar versión de Nginx
    server_tokens off;

    location = /favicon.ico { access_log off; log_not_found off; }
    
    location /static/ {
        alias /var/www/tienda_heilyn/staticfiles/;
    }

    location /media/ {
        alias /var/www/tienda_heilyn/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn-tienda.sock;
    }
}
